### ISSUE TITLE
setup step 11 (paver) fails

### ISSUE THREAD

**Issue by flip111** [seanfisk/python-project-template#45]
```
---> pavement.test_all


Captured Task Output:
---------------------

---> pavement.test_all
Traceback (most recent call last):
  File "/home/flip111/python/myproject/venv/lib64/python3.6/site-packages/paver/tasks.py", line 195, in _run_task
    return do_task()
  File "/home/flip111/python/myproject/venv/lib64/python3.6/site-packages/paver/tasks.py", line 192, in do_task
    return func(**kw)
  File "pavement.py", line 114, in test_all
    retcode = _test_all()
  File "./setup.py", line 196, in _test_all
    return _lint() + _test()
  File "./setup.py", line 169, in _lint
    project_python_files = [filename for filename in get_project_files()
  File "./setup.py", line 170, in <listcomp>
    if filename.endswith(b'.py')]
TypeError: endswith first arg must be str or a tuple of str, not bytes

```

python 3.6.2

**Comment by trentbullard** [comment]
on python 3.6.1 TypeError: a bytes-like object is required, not 'str'

**Comment by AmrAbdullatif** [comment]
Please confirm my correction:
For python version>=3.6
Go to line 456 ---> arg==arg
Change it to ---> arg==str(arg)

Please also update packages in requirement-dev.txt file to the current version

Have fun :)

**Comment by pierluigi-failla** [comment]
Same error after updating to `Paver==1.2.4` using Python 3.6.x 

@AmrAbdullatif where should be added your fix?
